2019-02-10 09:07:16.029 INFO [main]com.example.phone.PhoneApplication.logStarting:50 -Starting PhoneApplication on DESKTOP-CNBG6IH with PID 16456 (H:\peixun\target\classes started by ligengxian in H:\peixun)
2019-02-10 09:07:16.031 INFO [main]com.example.phone.PhoneApplication.logStartupProfileInfo:675 -No active profile set, falling back to default profiles: default
2019-02-10 09:07:17.024 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-02-10 09:07:17.027 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-02-10 09:07:17.054 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 8ms. Found 0 repository interfaces.
2019-02-10 09:07:17.399 INFO [main]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$ab30ecb1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-10 09:07:17.822 INFO [main]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-02-10 09:07:17.838 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-02-10 09:07:17.858 INFO [main]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-02-10 09:07:17.859 INFO [main]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-02-10 09:07:17.865 INFO [main]org.apache.catalina.core.AprLifecycleListener.log:173 -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [E:\jdk1.8\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;E:\oracle\app\oracle\product\10.2.0\server\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_91\bin;C:\Program Files\Java\jdk1.8.0_91\jre\bin;H:\maven\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\git\Git\cmd;C:\Program Files\Redis\;C:\WINDOWS\System32\OpenSSH\;C:\Python27;E:\ngrock0\ngrok1\windows_386;E:\es\elasticsearch-5.6.8\bin;JAVA_OPTS=-Xms64m -Xmx512;H:\gradle\gradle-4.1\bin;C:\Program Files\Redis;"C:\Program Files\Java\jdk1.8.0_91\bin;C:\Program Files\Java\jdk1.8.0_91\jre\bin";C:\Program Files (x86)\MySQL\MySQL Server 5.5\bin;C:\Users\ligengxian\AppData\Local\Microsoft\WindowsApps;;.]
2019-02-10 09:07:18.808 INFO [main]o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log:173 -Initializing Spring embedded WebApplicationContext
2019-02-10 09:07:18.809 INFO [main]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:296 -Root WebApplicationContext: initialization completed in 2712 ms
2019-02-10 09:07:19.668 INFO [main]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-02-10 09:07:20.030 WARN [main]o.s.b.a.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists:70 -Cannot find template location(s): [classpath:/templates] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)
2019-02-10 09:07:20.111 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-02-10 09:07:20.144 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Pausing ProtocolHandler ["http-nio-8080"]
2019-02-10 09:07:20.145 INFO [main]org.apache.catalina.core.StandardService.log:173 -Stopping service [Tomcat]
2019-02-10 09:07:20.149 INFO [main]org.apache.catalina.util.LifecycleBase.log:173 -The stop() method was called on component [StandardServer[-1]] after stop() had already been called. The second call will be ignored.
2019-02-10 09:07:20.149 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Stopping ProtocolHandler ["http-nio-8080"]
2019-02-10 09:07:20.149 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Destroying ProtocolHandler ["http-nio-8080"]
2019-02-10 09:07:20.151 INFO [main]o.s.b.a.logging.ConditionEvaluationReportLoggingListener.logMessage:142 -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-02-10 09:07:20.157 INFO [main]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.shutdown:208 -Shutting down ExecutorService 'applicationTaskExecutor'
2019-02-10 09:07:58.011 INFO [main]com.example.phone.PhoneApplication.logStarting:50 -Starting PhoneApplication on DESKTOP-CNBG6IH with PID 6544 (H:\peixun\target\classes started by ligengxian in H:\peixun)
2019-02-10 09:07:58.018 INFO [main]com.example.phone.PhoneApplication.logStartupProfileInfo:675 -No active profile set, falling back to default profiles: default
2019-02-10 09:07:58.595 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-02-10 09:07:58.601 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-02-10 09:07:58.621 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 8ms. Found 0 repository interfaces.
2019-02-10 09:07:58.880 INFO [main]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$e4712863] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-10 09:07:59.173 INFO [main]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-02-10 09:07:59.184 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-02-10 09:07:59.194 INFO [main]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-02-10 09:07:59.195 INFO [main]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-02-10 09:07:59.200 INFO [main]org.apache.catalina.core.AprLifecycleListener.log:173 -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [E:\jdk1.8\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;E:\oracle\app\oracle\product\10.2.0\server\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_91\bin;C:\Program Files\Java\jdk1.8.0_91\jre\bin;H:\maven\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\git\Git\cmd;C:\Program Files\Redis\;C:\WINDOWS\System32\OpenSSH\;C:\Python27;E:\ngrock0\ngrok1\windows_386;E:\es\elasticsearch-5.6.8\bin;JAVA_OPTS=-Xms64m -Xmx512;H:\gradle\gradle-4.1\bin;C:\Program Files\Redis;"C:\Program Files\Java\jdk1.8.0_91\bin;C:\Program Files\Java\jdk1.8.0_91\jre\bin";C:\Program Files (x86)\MySQL\MySQL Server 5.5\bin;C:\Users\ligengxian\AppData\Local\Microsoft\WindowsApps;;.]
2019-02-10 09:07:59.284 INFO [main]o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log:173 -Initializing Spring embedded WebApplicationContext
2019-02-10 09:07:59.285 INFO [main]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:296 -Root WebApplicationContext: initialization completed in 1210 ms
2019-02-10 09:07:59.859 INFO [main]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-02-10 09:08:00.106 WARN [main]o.s.b.a.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists:70 -Cannot find template location(s): [classpath:/templates] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)
2019-02-10 09:08:00.179 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-02-10 09:08:00.207 INFO [main]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:204 -Tomcat started on port(s): 8080 (http) with context path ''
2019-02-10 09:08:00.209 INFO [main]com.example.phone.PhoneApplication.logStarted:59 -Started PhoneApplication in 2.606 seconds (JVM running for 3.258)
2019-02-10 09:09:23.222 INFO [http-nio-8080-exec-1]o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-02-10 09:09:23.223 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-02-10 09:09:23.229 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 6 ms
2019-02-10 09:09:23.706 INFO [http-nio-8080-exec-2]com.zaxxer.hikari.HikariDataSource.getConnection:110 -HikariPool-1 - Starting...
2019-02-10 09:09:23.839 INFO [http-nio-8080-exec-2]com.zaxxer.hikari.HikariDataSource.getConnection:123 -HikariPool-1 - Start completed.
2019-02-10 09:09:24.035 INFO [http-nio-8080-exec-2]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-02-10 09:09:24.036 INFO [http-nio-8080-exec-2]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-02-10 10:11:06.139 INFO [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.CommandHandler.log:219 -null Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-02-10 10:11:06.255 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /127.0.0.1:6379
2019-02-10 10:11:07.268 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:11:11.754 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:11:12.758 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:11:16.954 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:11:17.957 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:11:22.154 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:11:23.158 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:11:27.355 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:11:28.360 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:11:36.555 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:11:37.561 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:11:53.955 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:11:54.960 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:12:25.054 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:12:26.058 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:12:56.155 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:12:56.158 INFO [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 127.0.0.1:6379
2019-02-10 10:25:41.642 INFO [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.CommandHandler.log:219 -null Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-02-10 10:25:41.654 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /127.0.0.1:6379
2019-02-10 10:25:42.659 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:25:47.155 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:25:48.158 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:25:52.354 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:25:53.358 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:25:57.555 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:25:58.557 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:26:02.754 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:26:03.757 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:26:11.953 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:26:12.956 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:26:29.354 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:26:30.359 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:27:00.455 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:27:01.457 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:27:31.554 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:27:32.557 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:28:02.654 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:28:03.656 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:28:33.754 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:28:34.758 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:29:04.854 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:29:04.856 INFO [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 127.0.0.1:6379
2019-02-10 10:39:32.956 INFO [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.CommandHandler.log:219 -null Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-02-10 10:39:33.061 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /127.0.0.1:6379
2019-02-10 10:39:34.078 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:39:38.752 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:39:39.769 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:39:43.958 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:39:44.974 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:39:49.162 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:39:50.179 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:39:54.367 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:39:55.385 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:40:03.655 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:40:04.658 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:40:21.055 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:40:22.073 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:40:52.168 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:40:53.186 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:41:23.263 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:41:24.294 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:41:54.368 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:41:55.386 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:42:25.466 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:42:26.503 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:42:56.549 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:42:57.565 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:43:27.670 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:43:28.702 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:43:58.760 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:43:59.777 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:44:29.855 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:44:30.871 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:45:00.957 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:45:01.974 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:45:32.054 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:45:32.054 INFO [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 127.0.0.1:6379
2019-02-10 10:47:05.721 INFO [main]com.example.phone.PhoneApplication.logStarting:50 -Starting PhoneApplication on DESKTOP-CNBG6IH with PID 14804 (H:\peixun\target\classes started by ligengxian in H:\peixun)
2019-02-10 10:47:05.724 INFO [main]com.example.phone.PhoneApplication.logStartupProfileInfo:675 -No active profile set, falling back to default profiles: default
2019-02-10 10:47:06.471 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-02-10 10:47:06.473 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-02-10 10:47:06.494 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 6ms. Found 0 repository interfaces.
2019-02-10 10:47:06.801 INFO [main]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$526c2c8e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-10 10:47:07.175 INFO [main]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-02-10 10:47:07.189 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-02-10 10:47:07.198 INFO [main]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-02-10 10:47:07.198 INFO [main]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-02-10 10:47:07.205 INFO [main]org.apache.catalina.core.AprLifecycleListener.log:173 -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [E:\jdk1.8\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;E:\oracle\app\oracle\product\10.2.0\server\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_91\bin;C:\Program Files\Java\jdk1.8.0_91\jre\bin;H:\maven\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\git\Git\cmd;C:\Program Files\Redis\;C:\WINDOWS\System32\OpenSSH\;C:\Python27;E:\ngrock0\ngrok1\windows_386;E:\es\elasticsearch-5.6.8\bin;JAVA_OPTS=-Xms64m -Xmx512;H:\gradle\gradle-4.1\bin;C:\Program Files\Redis;"C:\Program Files\Java\jdk1.8.0_91\bin;C:\Program Files\Java\jdk1.8.0_91\jre\bin";C:\Program Files (x86)\MySQL\MySQL Server 5.5\bin;C:\Users\ligengxian\AppData\Local\Microsoft\WindowsApps;;.]
2019-02-10 10:47:08.144 INFO [main]o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log:173 -Initializing Spring embedded WebApplicationContext
2019-02-10 10:47:08.145 INFO [main]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:296 -Root WebApplicationContext: initialization completed in 2322 ms
2019-02-10 10:47:09.098 INFO [main]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-02-10 10:47:09.363 WARN [main]o.s.b.a.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists:70 -Cannot find template location(s): [classpath:/templates] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)
2019-02-10 10:47:09.439 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-02-10 10:47:09.459 INFO [main]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:204 -Tomcat started on port(s): 8080 (http) with context path ''
2019-02-10 10:47:09.461 INFO [main]com.example.phone.PhoneApplication.logStarted:59 -Started PhoneApplication in 4.489 seconds (JVM running for 6.82)
2019-02-10 10:47:18.419 INFO [http-nio-8080-exec-1]o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-02-10 10:47:18.420 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-02-10 10:47:18.427 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 7 ms
2019-02-10 10:47:20.691 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-02-10 10:47:20.692 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-02-10 10:47:34.511 INFO [http-nio-8080-exec-3]com.zaxxer.hikari.HikariDataSource.getConnection:110 -HikariPool-1 - Starting...
2019-02-10 10:47:34.640 INFO [http-nio-8080-exec-3]com.zaxxer.hikari.HikariDataSource.getConnection:123 -HikariPool-1 - Start completed.
2019-02-10 10:48:29.432 INFO [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.CommandHandler.log:219 -null Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-02-10 10:48:29.540 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /127.0.0.1:6379
2019-02-10 10:48:30.547 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:48:35.040 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:48:36.043 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:48:40.240 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:48:41.243 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:48:45.440 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:48:46.443 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 10:48:50.639 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 10:48:50.641 INFO [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 127.0.0.1:6379
2019-02-10 12:55:22.130 INFO [main]com.example.phone.PhoneApplication.logStarting:50 -Starting PhoneApplication on DESKTOP-CNBG6IH with PID 1384 (H:\peixun\target\classes started by ligengxian in H:\peixun)
2019-02-10 12:55:22.202 INFO [main]com.example.phone.PhoneApplication.logStartupProfileInfo:675 -No active profile set, falling back to default profiles: default
2019-02-10 12:55:22.940 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-02-10 12:55:22.944 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-02-10 12:55:22.970 INFO [main]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 10ms. Found 0 repository interfaces.
2019-02-10 12:55:23.271 INFO [main]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$cd0807de] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-02-10 12:55:23.747 INFO [main]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-02-10 12:55:23.763 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-02-10 12:55:23.772 INFO [main]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-02-10 12:55:23.772 INFO [main]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.14]
2019-02-10 12:55:23.778 INFO [main]org.apache.catalina.core.AprLifecycleListener.log:173 -The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [E:\jdk1.8\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;E:\oracle\app\oracle\product\10.2.0\server\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_91\bin;C:\Program Files\Java\jdk1.8.0_91\jre\bin;H:\maven\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\git\Git\cmd;C:\Program Files\Redis\;C:\WINDOWS\System32\OpenSSH\;C:\Python27;E:\ngrock0\ngrok1\windows_386;E:\es\elasticsearch-5.6.8\bin;JAVA_OPTS=-Xms64m -Xmx512;H:\gradle\gradle-4.1\bin;C:\Program Files\Redis;"C:\Program Files\Java\jdk1.8.0_91\bin;C:\Program Files\Java\jdk1.8.0_91\jre\bin";C:\Program Files (x86)\MySQL\MySQL Server 5.5\bin;C:\Users\ligengxian\AppData\Local\Microsoft\WindowsApps;;.]
2019-02-10 12:55:23.866 INFO [main]o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log:173 -Initializing Spring embedded WebApplicationContext
2019-02-10 12:55:23.867 INFO [main]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:296 -Root WebApplicationContext: initialization completed in 1588 ms
2019-02-10 12:55:24.634 INFO [main]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-02-10 12:55:24.933 WARN [main]o.s.b.a.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists:70 -Cannot find template location(s): [classpath:/templates] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)
2019-02-10 12:55:25.013 INFO [main]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-02-10 12:55:25.033 INFO [main]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:204 -Tomcat started on port(s): 8080 (http) with context path ''
2019-02-10 12:55:25.035 INFO [main]com.example.phone.PhoneApplication.logStarted:59 -Started PhoneApplication in 3.912 seconds (JVM running for 5.768)
2019-02-10 12:55:34.916 INFO [http-nio-8080-exec-1]o.a.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-02-10 12:55:34.919 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-02-10 12:55:34.934 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 14 ms
2019-02-10 12:55:35.167 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-02-10 12:55:35.169 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-02-10 14:44:25.823 INFO [http-nio-8080-exec-6]com.zaxxer.hikari.HikariDataSource.getConnection:110 -HikariPool-1 - Starting...
2019-02-10 14:44:25.987 INFO [http-nio-8080-exec-6]com.zaxxer.hikari.HikariDataSource.getConnection:123 -HikariPool-1 - Start completed.
2019-02-10 20:32:26.558 INFO [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.CommandHandler.log:219 -null Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
2019-02-10 20:32:26.687 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /127.0.0.1:6379
2019-02-10 20:32:27.847 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:32:32.286 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:32:33.289 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:32:37.487 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:32:38.491 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:32:42.687 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:32:43.690 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:32:47.887 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:32:48.889 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:32:57.087 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:32:58.090 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:33:14.485 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:33:15.489 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:33:45.585 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:33:46.590 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:34:16.686 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:34:17.690 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:34:47.786 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:34:48.789 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:35:18.887 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:35:19.891 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:35:49.987 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:35:50.990 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:36:21.087 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:36:22.091 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:36:52.185 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:36:53.189 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:37:23.285 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:37:24.289 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:37:54.385 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:37:55.389 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:38:25.485 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:38:26.489 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:38:56.586 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:38:57.589 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:39:27.686 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:39:28.690 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:39:58.787 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:39:59.791 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:40:29.885 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:40:30.890 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:41:00.985 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:41:01.988 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:41:32.085 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:41:33.090 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:42:03.185 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:42:04.190 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:42:34.286 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:42:35.290 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:43:05.386 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:43:06.389 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:43:36.487 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:43:37.490 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:44:07.587 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:44:08.590 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:44:38.687 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:44:39.690 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:45:09.785 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:45:10.788 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:45:40.885 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:45:41.889 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:46:11.985 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:46:12.992 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:46:43.085 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:46:44.089 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:47:14.186 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:47:15.190 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:47:45.286 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:47:46.290 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:48:16.386 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:48:17.389 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:48:47.487 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:48:48.491 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:49:18.587 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:49:19.591 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:49:49.685 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:49:50.688 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:50:20.786 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:50:21.789 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:50:51.885 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:50:52.890 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:51:22.986 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:51:23.990 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:51:54.085 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:51:55.089 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:52:25.186 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:52:26.189 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:52:56.286 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:52:57.289 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:53:27.387 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:53:28.390 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:53:58.487 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:53:59.490 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:54:29.587 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:54:30.590 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:55:00.687 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:55:01.690 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:55:31.785 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:55:32.787 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:56:02.885 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:56:03.889 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:56:33.986 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:56:34.988 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:57:05.085 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:57:06.090 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:57:36.186 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:57:37.189 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:58:07.286 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:58:08.290 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:58:38.386 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:58:39.389 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:59:09.487 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:59:10.490 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 20:59:40.587 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 20:59:41.589 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:00:11.687 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:00:12.689 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:00:42.785 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:00:43.789 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:01:13.885 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:01:14.889 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:01:44.985 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:01:45.989 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:02:16.085 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:02:17.090 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:02:47.186 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:02:48.190 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:03:18.286 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:03:19.291 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:03:49.386 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:03:50.389 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:04:20.487 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:04:21.491 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:04:51.587 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:04:52.592 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:05:22.685 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:05:23.689 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:05:53.786 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:05:54.789 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:06:24.885 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:06:25.889 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:06:55.985 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:06:56.990 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:07:27.085 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:07:28.091 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:07:58.186 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:07:59.189 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:08:29.286 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:08:30.290 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:09:00.387 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:09:01.390 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:09:31.487 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:09:32.489 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:10:02.588 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:10:03.597 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:10:33.686 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:10:34.692 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:11:04.785 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:11:05.789 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:11:35.885 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:11:36.888 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:12:06.985 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:12:07.987 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:12:38.085 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:12:39.089 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:13:09.186 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:13:10.190 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:13:40.285 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:13:41.288 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:14:11.386 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:14:12.390 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:14:42.487 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:14:43.490 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:15:13.587 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:15:14.592 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:15:44.685 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:15:45.688 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:16:15.785 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:16:16.792 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:16:46.885 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:16:47.889 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:17:17.985 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:17:18.988 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:17:49.086 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:17:50.089 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:18:20.186 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:18:21.189 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:18:51.286 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:18:52.289 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:19:22.387 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:19:23.389 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:19:53.487 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:19:54.490 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:20:24.585 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:20:25.589 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:20:55.685 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:20:56.688 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:21:26.785 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:21:27.789 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:21:57.885 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:21:58.889 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:22:28.985 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:22:29.987 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:23:00.086 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:23:01.089 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:23:31.186 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:23:32.192 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:24:02.287 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:24:03.291 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:24:33.387 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:24:34.391 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:25:04.485 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:25:05.489 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:25:35.585 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:25:36.588 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:26:06.685 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:26:07.698 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:26:37.785 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:26:38.790 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:27:08.885 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:27:09.888 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:27:39.986 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:27:40.990 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:28:11.086 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:28:12.090 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:28:42.186 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:28:43.188 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:29:13.287 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:29:14.291 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:29:44.387 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:29:45.391 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:30:15.485 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:30:16.488 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:30:46.586 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:30:47.589 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:31:17.686 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:31:18.704 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:31:48.787 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:31:49.791 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:32:19.887 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:32:20.889 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:32:50.985 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:32:51.989 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:33:22.086 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:33:23.089 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:33:53.186 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:33:54.190 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:34:24.286 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:34:25.292 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:34:55.386 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:34:56.389 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:35:26.487 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:35:27.490 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:35:57.587 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:35:58.592 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:36:28.685 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:36:29.688 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:36:59.785 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:37:00.788 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:37:30.885 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:37:31.889 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:38:01.986 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:38:02.989 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:38:33.086 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:38:34.089 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:39:04.185 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:39:05.189 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:39:35.286 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:39:36.287 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:40:06.387 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:40:07.389 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:40:37.487 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:40:38.490 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:41:08.585 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:41:09.589 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:41:39.685 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:41:40.689 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:42:10.786 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:42:11.788 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:42:41.887 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:42:42.889 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:43:12.985 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:43:13.989 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:43:44.085 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:43:45.093 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:44:15.185 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:44:16.188 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:44:46.286 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:44:47.290 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:45:17.386 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:45:18.391 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:45:48.487 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:45:49.489 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:46:19.585 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:46:20.590 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:46:50.687 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:46:51.690 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:47:21.786 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:47:22.787 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:47:52.885 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:47:53.889 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:48:23.985 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:48:24.988 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:48:55.085 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:48:56.089 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:49:26.185 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:49:27.189 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:49:57.286 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:49:58.290 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:50:28.386 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:50:29.389 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:50:59.487 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:51:00.490 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:51:30.587 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:51:31.591 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:52:01.687 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:52:02.690 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:52:32.785 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:52:33.788 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:53:03.885 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:53:04.888 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:53:34.985 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:53:35.989 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:54:06.085 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:54:07.090 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:54:37.186 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:54:38.189 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:55:08.286 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:55:09.289 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:55:39.386 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:55:40.390 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:56:10.487 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:56:11.490 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:56:41.587 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:56:42.590 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:57:12.685 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:57:13.688 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:57:43.786 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:57:44.788 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:58:14.885 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:58:15.888 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:58:45.985 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:58:46.989 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:59:17.085 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:59:18.089 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 21:59:48.186 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 21:59:49.190 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:00:19.286 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:00:20.290 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:00:50.387 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:00:51.391 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:01:21.487 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:01:22.490 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:01:52.587 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:01:53.590 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:02:23.685 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:02:24.687 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:02:54.786 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:02:55.790 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:03:25.885 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:03:26.888 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:03:56.985 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:03:58.000 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:04:28.086 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:04:29.089 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:04:59.186 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:05:00.189 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:05:30.286 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:05:31.289 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:06:01.387 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:06:02.390 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:06:32.487 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:06:33.490 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:07:03.587 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:07:04.589 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:07:34.685 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:07:35.688 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:08:05.785 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:08:06.788 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:08:36.885 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:08:37.889 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:09:07.985 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:09:08.988 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:09:39.086 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:09:40.090 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:10:10.186 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:10:11.189 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:10:41.286 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:10:42.300 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:11:12.387 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:11:13.390 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:11:43.487 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:11:44.491 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:12:14.585 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:12:15.587 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:12:45.686 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:12:46.689 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:13:16.785 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:13:17.788 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:13:47.885 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:13:48.889 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:14:18.986 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:14:19.991 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:14:50.086 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:14:51.089 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:15:21.186 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:15:22.189 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:15:52.286 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:15:53.290 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:16:23.387 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:16:24.390 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:16:54.487 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:16:55.490 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:17:25.586 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:17:26.588 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:17:56.685 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:17:57.689 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:18:27.785 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:18:28.788 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:18:58.885 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:18:59.890 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:19:29.986 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:19:30.990 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:20:01.086 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:20:02.088 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:20:32.186 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:20:33.189 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:21:03.287 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:21:04.290 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:21:34.387 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:21:35.390 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:22:05.485 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:22:06.487 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:22:36.586 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:22:37.588 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:23:07.685 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:23:08.687 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:23:38.785 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:23:39.788 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:24:09.885 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:24:10.889 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:24:40.986 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:24:41.989 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:25:12.086 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:25:13.088 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:25:43.187 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:25:44.190 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:26:14.287 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:26:15.290 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:26:45.387 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:26:46.389 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:27:16.485 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:27:17.500 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:27:47.586 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:27:48.589 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:28:18.685 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:28:19.688 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:28:49.785 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:28:50.790 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:29:20.885 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:29:21.889 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:29:51.987 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:29:52.991 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:30:23.085 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:30:24.089 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:30:54.187 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:30:55.191 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:31:25.287 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:31:26.291 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:31:56.387 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:31:57.389 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:32:27.486 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:32:28.487 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:32:58.585 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:32:59.588 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:33:29.685 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:33:30.689 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:34:00.785 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:34:01.791 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:34:31.886 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:34:32.888 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:35:02.986 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:35:04.001 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:35:34.086 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:35:35.089 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:36:05.185 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:36:06.188 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:36:36.285 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:36:37.289 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:37:07.386 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:37:08.388 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:37:38.486 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:37:39.490 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:38:09.586 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:38:10.590 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:38:40.686 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:38:41.690 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:39:11.787 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:39:12.789 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:39:42.885 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:39:43.888 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:40:13.985 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:40:14.988 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:40:45.087 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:40:46.090 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:41:16.187 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:41:17.189 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:41:47.286 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:41:48.289 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:42:18.385 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:42:19.389 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:42:49.485 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:42:50.488 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:43:20.586 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:43:21.588 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:43:51.686 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:43:52.689 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:44:22.787 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:44:23.791 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:44:53.886 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:44:54.888 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:45:24.986 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:45:25.988 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:45:56.087 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:45:57.088 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:46:27.185 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:46:28.188 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:46:58.285 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:46:59.288 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:47:29.385 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:47:30.388 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:48:00.485 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:48:01.489 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:48:31.585 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:48:32.589 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:49:02.686 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:49:03.689 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:49:33.786 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:49:34.790 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:50:04.886 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:50:05.889 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:50:35.986 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:50:36.988 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:51:07.087 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:51:08.089 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:51:38.186 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:51:39.189 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:52:09.285 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:52:10.288 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:52:40.385 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:52:41.388 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:53:11.485 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:53:12.488 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:53:42.585 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:53:43.589 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:54:13.686 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:54:14.692 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:54:44.786 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:54:45.789 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:55:15.887 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:55:16.890 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:55:46.987 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:55:47.990 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:56:18.085 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:56:19.094 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:56:49.187 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:56:50.192 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:57:20.287 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:57:21.290 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:57:51.386 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:57:52.388 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:58:22.485 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:58:23.488 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:58:53.585 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:58:54.588 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:59:24.685 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:59:25.689 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 22:59:55.786 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 22:59:56.789 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:01:16.222 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:01:17.224 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:01:47.322 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:01:48.326 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:02:18.422 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:02:19.425 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:02:49.521 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:02:50.524 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:03:20.620 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:03:21.626 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:03:51.721 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:03:52.725 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:04:22.821 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:04:23.826 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:04:53.922 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:04:54.924 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:05:25.022 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:05:26.025 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:05:56.123 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:05:57.127 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:06:27.223 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:06:28.226 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:06:58.323 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:06:59.326 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:07:29.420 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:07:30.425 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:08:00.521 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:08:01.523 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:08:31.621 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:08:32.625 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:09:02.721 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:09:03.724 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:09:33.821 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:09:34.823 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:10:04.922 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:10:05.926 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:10:36.022 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:10:37.025 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:11:07.123 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:11:08.127 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:11:38.223 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:11:39.227 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:12:09.323 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:12:10.326 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:12:40.421 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:12:41.424 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:13:11.522 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:13:12.524 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:13:42.621 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:13:43.625 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:14:13.721 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:14:14.723 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:14:44.822 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:14:45.826 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:15:15.921 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:15:16.924 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:15:47.022 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:15:48.025 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:16:18.123 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:16:19.126 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:16:49.223 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:16:50.226 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:17:20.320 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:17:21.324 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:17:51.422 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:17:52.426 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:18:22.521 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:18:23.525 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:18:53.621 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:18:54.624 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:19:24.721 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:19:25.724 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:19:55.822 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:19:56.825 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:20:26.923 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:20:27.926 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:20:58.023 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:20:59.026 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:21:29.123 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:21:30.126 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:22:00.222 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:22:01.225 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:22:31.320 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:22:32.335 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:23:02.421 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:23:03.424 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:23:33.521 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:23:34.525 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:24:04.621 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:24:05.624 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:24:35.721 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:24:36.725 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:25:06.822 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:25:07.825 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:25:37.922 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:25:38.925 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
2019-02-10 23:26:09.023 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 127.0.0.1:6379
2019-02-10 23:26:10.026 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6379
